name: places_elementary
version: "0.0.1"
description: a Flutter template project for development.
publish_to: none

dependencies:
  cached_network_image: ^3.2.0
  dio: ^4.0.4
  elementary: ^1.0.0
  firebase_crashlytics: ^2.3.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^1.0.0
  intl: ^0.17.0
  logger: ^1.1.0
  objectbox: ^1.3.0
  objectbox_flutter_libs: ^1.3.0
  path_provider: ^2.0.8
  photo_view: ^0.13.0
  provider: ^6.0.1
  retrofit: ^3.0.0
  shared_preferences: ^2.0.12
  shimmer: ^2.0.0
  surf_logger: ^1.0.1
  surf_util: ^1.0.3

dev_dependencies:
  build_runner: ^2.1.5
  dart_code_metrics: ^4.7.0
  elementary_test: ^1.0.1
  flutter_test:
    sdk: flutter
  freezed: ^1.1.0
  freezed_annotation: ^1.1.0
  json_serializable: ^6.1.1
  objectbox_generator: any
  retrofit_generator: ^3.0.0
  surf_lint_rules: ^1.4.1

environment:
  sdk: ">=2.14.0-0 <3.0.0"

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/
    - assets/icons/
    - assets/icons/catalog/
    - assets/icons/tutorial/
    - assets/icons/empty_pages/
    - assets/icons/loader/
    - assets/icons/map/
    - assets/images/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Thin.ttf
          weight: 100
        - asset: assets/fonts/Roboto-Light.ttf
          weight: 300
        - asset: assets/fonts/Roboto-Regular.ttf
          weight: 400
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/Roboto-Black.ttf
          weight: 900
        - asset: assets/fonts/Roboto-ThinItalic.ttf
          weight: 100
          style: italic
        - asset: assets/fonts/Roboto-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/Roboto-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/Roboto-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Roboto-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/Roboto-BlackItalic.ttf
          weight: 900
          style: italic
